module.exports = [
    {
        firstName: "mariano",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "mariano.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "luca",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "luca.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "kerly",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "kerly.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "marian",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "marian.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "sol",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "sol.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "dani",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "dani.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "brian",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "brian.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
    {
        firstName: "rena",
        lastName: null,
        phoneNumber: null,
        address: null,
        city: null,
        country: null,
        zipCode: null,
        email: "rena.admin@sportvibe.com",
        password: "Henry123.",
        image: null,
        externalSignIn: false,
        rol: "admin"
    },
]